# Generated by Django 5.2.15 on 2026-07-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-ключ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL-ключ')),
                ('construction_type', models.CharField(choices=[('timber', 'Брус'), ('frame', 'Каркас'), ('log', 'Бревно'), ('other', 'Другое')], default='timber', max_length=30, verbose_name='Тип строительства')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь, м²')),
                ('floors', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Этажность')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Спальни')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина, м')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина, м')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от, ₽')),
                ('build_days_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок строительства от, дней')),
                ('build_days_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок строительства до, дней')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='projects/main/', verbose_name='Главное изображение')),
                ('characteristics', models.JSONField(blank=True, default=dict, help_text='Например: {"Материал стен": "Брус 140x190", "Фундамент": "Сваи"}', verbose_name='Дополнительные характеристики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый проект')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проекта',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название комплектации')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от, ₽')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Параметр')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.projectpackage', verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Пункт комплектации',
                'verbose_name_plural': 'Пункты комплектации',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Планировка', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='projects/plans/', verbose_name='Планировка')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='Этаж')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'ordering': ['sort_order', 'floor'],
            },
        ),
    ]
