# Generated by Django 5.2.15 on 2026-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, help_text='Например: H-001, B-002, G-003. Нужен для обновления проекта через Excel.', max_length=50, null=True, unique=True, verbose_name='Код проекта из Excel'),
        ),
    ]
