# Generated by Django 5.2.15 on 2026-07-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_project_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='projectpackageitem',
            name='package',
        ),
        migrations.AddField(
            model_name='project',
            name='floor_label',
            field=models.CharField(blank=True, help_text='Например: Полутораэтажный, Одноэтажный, Двухэтажный', max_length=100, verbose_name='Этажность текстом'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='project',
            name='size_text',
            field=models.CharField(blank=True, help_text='Например: 6х6, 6х8, 8х9', max_length=50, verbose_name='Размер текстом'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('facade', 'Фасад'), ('gallery', 'Галерея'), ('detail', 'Деталь'), ('interior', 'Интерьер'), ('other', 'Другое')], default='gallery', max_length=30, verbose_name='Тип изображения'),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt-текст'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, help_text='Например: DB-01, BATH-02, GARAGE-03', max_length=50, null=True, unique=True, verbose_name='Код проекта из Excel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floors',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Например: 1, 1.5, 2', max_digits=3, null=True, verbose_name='Этажность числом'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='URL-ключ'),
        ),
        migrations.AlterField(
            model_name='projectpackage',
            name='title',
            field=models.CharField(help_text='Например: Комплектация дома из бруса "ПОД УСАДКУ"', max_length=255, verbose_name='Название комплектации'),
        ),
        migrations.AlterField(
            model_name='projectpackageitem',
            name='value',
            field=models.TextField(blank=True, verbose_name='Значение'),
        ),
        migrations.CreateModel(
            name='ProjectAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(help_text='Например: Фундамент, Кровля', max_length=255, verbose_name='Группа')),
                ('title', models.CharField(max_length=255, verbose_name='Название опции')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, ₽')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Дополнительная опция',
                'verbose_name_plural': 'Дополнительные опции',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Высота, Силовые конструкции, Прочее', max_length=255, verbose_name='Название раздела')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.projectpackage', verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Раздел комплектации',
                'verbose_name_plural': 'Разделы комплектации',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectpackageitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.projectpackagesection', verbose_name='Раздел комплектации'),
        ),
        migrations.CreateModel(
            name='ProjectPriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(help_text='Например: Обычный брус, Профилированный брус', max_length=255, verbose_name='Группа')),
                ('title', models.CharField(help_text='Например: Обычный брус 150х150', max_length=255, verbose_name='Название варианта')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, ₽')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Цена по материалу',
                'verbose_name_plural': 'Цены по материалам',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
