# Generated by Django 5.2.15 on 2026-07-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_project_characteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Текстовый раздел проекта',
                'verbose_name_plural': 'Текстовые разделы проекта',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIllustratedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(blank=True, default='', help_text='Например: Фундамент, Кровля, Материалы', max_length=255, verbose_name='Группа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='catalog/project_options/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrated_options', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Иллюстрированная опция проекта',
                'verbose_name_plural': 'Иллюстрированные опции проекта',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
