"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    # Тема админки — обязательно до django.contrib.admin, иначе шаблоны
    # jazzmin не переопределят стандартные.
    "jazzmin",
    # Свой AdminConfig вместо голого "django.contrib.admin" — подключает
    # BrusodelAdminSite (сводка на главной странице админки, см.
    # config/admin_site.py), не меняя ничего в самих admin.py по проекту.
    "config.apps.BrusodelAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "import_export",
    "axes",

    "catalog",
    "leads",
    "content",
    "seo",
    "calculator",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Обязательно последним — django-axes считает попытки входа в /admin/
    # и блокирует перебор пароля (152-ФЗ: техническая защита панели,
    # через которую доступны все ПДн заявок).
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Блокировка входа в админку после подряд неудачных попыток — вместо
# неограниченного числа попыток подобрать пароль, которое было раньше.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # час
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # templates/admin/index.html — кастомная сводка на главной странице
        # админки (см. config/admin_site.py). DIRS проверяется раньше
        # APP_DIRS, поэтому этот шаблон переопределяет и стандартный, и
        # jazzmin-овский admin/index.html.
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Приватное хранилище вложений заявок (см. leads/storage.py). Не путать с
# MEDIA_ROOT: этот каталог не примонтирован в Caddy и не отдаётся напрямую —
# доступ только через авторизованный Django-view.
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Проектные статические файлы, не привязанные к конкретному приложению
# (сейчас — только логотип для админки, см. JAZZMIN_SETTINGS ниже).
STATICFILES_DIRS = [BASE_DIR / "static_source"]

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

# Нужны только когда EMAIL_BACKEND — smtp.EmailBackend (см. .env.prod.example
# и DEPLOYMENT.md > "Email-уведомления о заявках"). С console.EmailBackend
# (дефолт) эти настройки ни на что не влияют — письма просто пишутся в лог
# контейнера, наружу не уходят.
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
# По умолчанию — SSL на 465 (так работает Яндекс.Почта и большинство
# провайдеров без доп. настройки). Для STARTTLS на 587 переключите оба флага
# через .env.prod: EMAIL_USE_SSL=False, EMAIL_USE_TLS=True.
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_TIMEOUT = 10

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="no-reply@localhost",
)

LEAD_NOTIFICATION_EMAILS = env.list(
    "LEAD_NOTIFICATION_EMAILS",
    default=[],
)

# Секретный ключ Яндекс SmartCaptcha (см. leads/captcha.py). Публичный
# client-ключ для виджета живёт только на фронтенде (NEXT_PUBLIC_*) — сюда
# его добавлять не нужно. Пустое значение полностью отключает проверку
# (форма продолжает работать как раньше — так тесты и локальная разработка
# не ломаются без реального ключа).
SMARTCAPTCHA_SERVER_KEY = env("SMARTCAPTCHA_SERVER_KEY", default="")

# Публичный адрес фронтенда — нужен там, где бэкенд сам строит ссылки на
# страницы сайта (не на свои же API/медиа), например в YML-фиде для Яндекса
# (см. catalog/feeds.py). Совпадает с NEXT_PUBLIC_SITE_URL у фронтенда.
SITE_URL = env("SITE_URL", default="https://brusodel.ru")

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=False,
)
CSRF_COOKIE_SECURE = env.bool(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=False,
)
SECURE_HSTS_SECONDS = env.int(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Срок хранения персональных данных заявки (152-ФЗ ст. 5: нельзя хранить
# дольше, чем требуют цели обработки — сайт уже обещает это в /privacy,
# но раньше это ничем не было обеспечено технически). После истечения
# срока management-команда anonymize_old_leads стирает phone/message/
# ip_address/user_agent/вложения, оставляя обезличенную запись для
# статистики по источникам. Итоговое число должен подтвердить владелец
# бизнеса — 24 месяца это разумный дефолт для строительной ниши с долгим
# циклом принятия решения, а не жёсткое требование закона.
LEAD_RETENTION_MONTHS = env.int("LEAD_RETENTION_MONTHS", default=24)

REST_FRAMEWORK = {
    # ScopedRateThrottle не ограничивает вьюхи без throttle_scope — это
    # безопасный глобальный дефолт, реальный лимит задан только для приёма
    # заявок (см. LeadCreateAPIView.throttle_scope), чтобы не мешать
    # обычному чтению каталога.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "leads": env(
            "LEAD_THROTTLE_RATE",
            default="10/hour",
        ),
    },
}

# ---------------------------------------------------------------------------
# Тема админки (django-jazzmin). Только оформление и навигация — на права
# доступа, поведение форм и данные не влияет.
# ---------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Брусодел — админка",
    "site_header": "Брусодел",
    "site_brand": "Брусодел",
    "site_logo": "brand/brusoteka-logo.png",
    "login_logo": "brand/brusoteka-logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "brand/brusoteka-logo.png",
    "welcome_sign": "Панель управления сайтом «Брусодел»",
    "copyright": 'ООО "СтройДача"',
    "search_model": ["catalog.Project", "leads.Lead", "content.Review", "seo.LandingPage"],

    "topmenu_links": [
        {"name": "Открыть сайт", "url": "/", "new_window": True},
        {"model": "auth.user"},
    ],

    "show_sidebar": True,
    "navigation_expanded": False,
    "order_with_respect_to": [
        "catalog",
        "content",
        "leads",
        "seo",
        "calculator",
        "auth",
    ],

    # Иконки — Font Awesome 5 (идёт вместе с jazzmin), группы моделей без
    # своей иконки получают default_icon_children ниже.
    "icons": {
        "auth": "fas fa-user-shield",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "catalog.Project": "fas fa-home",
        "catalog.ProjectCategory": "fas fa-folder-open",
        "catalog.Material": "fas fa-tree",
        "catalog.BuildPackage": "fas fa-box-open",
        "catalog.FoundationType": "fas fa-layer-group",
        "catalog.RoofCovering": "fas fa-umbrella",
        "catalog.ExtraOption": "fas fa-plus-circle",
        "catalog.CostRate": "fas fa-ruble-sign",
        "catalog.PricingSettings": "fas fa-percentage",
        "catalog.PricingRule": "fas fa-sliders-h",
        "catalog.SitePromotion": "fas fa-bullhorn",
        "catalog.ConstructionStep": "fas fa-list-ol",
        "catalog.ProjectOffer": "fas fa-tags",
        "catalog.ProjectImage": "fas fa-images",
        "catalog.ProjectPlan": "fas fa-drafting-compass",

        "content.Review": "fas fa-star",
        "content.PortfolioProject": "fas fa-camera-retro",
        "content.FAQ": "fas fa-question-circle",
        "content.Advantage": "fas fa-check-circle",
        "content.WorkStep": "fas fa-tasks",
        "content.ContactLocation": "fas fa-map-marker-alt",
        "content.SocialLink": "fas fa-share-alt",

        "leads.Lead": "fas fa-inbox",
        "leads.LeadAttachment": "fas fa-paperclip",

        "seo.LandingPage": "fas fa-file-alt",

        "calculator.HouseCostProfile": "fas fa-calculator",
        "calculator.CalculatorMaterial": "fas fa-tree",
        "calculator.CalculatorFoundation": "fas fa-layer-group",
        "calculator.CalculatorRoofCovering": "fas fa-umbrella",
        "calculator.CalculatorSettings": "fas fa-sliders-h",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "leads.Lead": "vertical_tabs",
    },

    "custom_css": "admin/brusodel-admin.css",
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_flat_style": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "theme": "flatly",
    # "dark_mode_theme" (jazzmin 2.x) отключён в 3.x — заменён на этот ключ.
    # Форсируем light: фирменные цвета в brusodel-admin.css настроены и
    # проверены только под светлую тему, "auto" мог бы среагировать на
    # тёмную тему ОС и показать нетронутую тёмную AdminLTE вперемешку с
    # нашими зелёными переопределениями.
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
