services:
  db:
    image: postgres:16
    container_name: stroidacha_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stroidacha
      POSTGRES_USER: stroidacha_user
      POSTGRES_PASSWORD: stroidacha_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: