# Generated by Django 5.2.15 on 2026-07-10 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('location_type', models.CharField(choices=[('office', 'Офис'), ('production', 'Производство'), ('warehouse', 'Склад'), ('showroom', 'Шоурум'), ('other', 'Другое')], default='office', max_length=32, verbose_name='Тип точки')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='Режим работы')),
                ('map_embed_url', models.URLField(blank=True, help_text='URL из iframe Яндекс.Карт. Например: https://yandex.ru/map-widget/v1/?...', max_length=1000, verbose_name='Ссылка для встраивания карты')),
                ('map_link_url', models.URLField(blank=True, help_text='Обычная ссылка на Яндекс.Карты или Google Maps.', max_length=1000, verbose_name='Ссылка открыть карту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Контактная точка',
                'verbose_name_plural': 'Контактные точки',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Площадь')),
                ('size_text', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Материал')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('main_image', models.ImageField(blank=True, upload_to='portfolio/main/', verbose_name='Главное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Объект портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['sort_order', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('portfolio_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.portfolioproject', verbose_name='Объект портфолио')),
            ],
            options={
                'verbose_name': 'Фото портфолио',
                'verbose_name_plural': 'Фото портфолио',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
