# Generated by Django 5.2.15 on 2026-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_cleanup_legacy_public_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Показывается на превью объекта в портфолио. Отметьте только у одного фото.', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Резервный вариант. Если ниже в галерее отмечено «Главное фото», на превью объекта используется оно, а не это изображение.', upload_to='portfolio/main/', verbose_name='Главное изображение'),
        ),
    ]
