# Generated by Django 5.2.15 on 2026-08-27 21:01

from django.db import migrations, models


# Значения по умолчанию — те же, что раньше были зашиты в коде фронтенда
# (SocialLinks.tsx / process.env.NEXT_PUBLIC_*_URL), с которых теперь можно
# уйти через Django Admin, не пересобирая фронтенд.
DEFAULT_LINKS = [
    ("vk", "https://vk.com/", 0),
    ("max", "https://max.ru/", 1),
    ("whatsapp", "https://api.whatsapp.com/send?phone=79676801812", 2),
    ("telegram", "https://t.me/+79676801812", 3),
]


def seed_social_links(apps, schema_editor):
    SocialLink = apps.get_model("content", "SocialLink")
    for platform, url, sort_order in DEFAULT_LINKS:
        SocialLink.objects.get_or_create(
            platform=platform,
            defaults={"url": url, "sort_order": sort_order},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_portfolio_image_is_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('vk', 'ВКонтакте'), ('max', 'MAX'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], help_text='Иконка и подпись для платформы фиксированы в коде сайта — здесь редактируется только ссылка.', max_length=20, unique=True, verbose_name='Платформа')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_social_links, noop),
    ]
