# Generated by Django 5.2.15 on 2026-07-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_project_characteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Дома из бруса 6х6', max_length=255, verbose_name='Внутреннее название')),
                ('slug', models.SlugField(help_text='Например: doma-iz-brusa-6x6', max_length=255, unique=True, verbose_name='URL-ключ')),
                ('page_type', models.CharField(choices=[('service', 'Услуга'), ('size', 'Размер'), ('material', 'Материал'), ('region', 'Регион'), ('delivery', 'Доставка'), ('production', 'Производство'), ('custom', 'Произвольная')], default='custom', max_length=30, verbose_name='Тип страницы')),
                ('h1', models.CharField(help_text='Главный заголовок страницы', max_length=255, verbose_name='H1')),
                ('intro_text', models.TextField(blank=True, help_text='Короткий текст под первым экраном', verbose_name='Вводный текст')),
                ('main_text', models.TextField(blank=True, help_text='Основной SEO/коммерческий текст страницы', verbose_name='Основной текст')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(blank=True, help_text='Если выбрать категорию, можно связать страницу с домами/банями/гаражами', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='catalog.projectcategory', verbose_name='Категория проектов')),
                ('related_projects', models.ManyToManyField(blank=True, help_text='Проекты, которые нужно показать на странице', related_name='landing_pages', to='catalog.project', verbose_name='Связанные проекты')),
            ],
            options={
                'verbose_name': 'SEO-страница',
                'verbose_name_plural': 'SEO-страницы',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='seo.landingpage', verbose_name='SEO-страница')),
            ],
            options={
                'verbose_name': 'FAQ SEO-страницы',
                'verbose_name_plural': 'FAQ SEO-страницы',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
