# Generated by Django 5.2.15 on 2026-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_landingpage_menu_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='filter_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='См. подсказку у поля «Фильтр по ширине».', max_digits=6, null=True, verbose_name='Фильтр по длине, м'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='filter_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заполните вместе с «Фильтр по длине», чтобы каталог на странице показывал только проекты этого размера (например, 6х6). Если оставить пустым, каталог покажет все проекты выбранной категории — это годится для страниц-хабов вроде «Дома из бруса», но не для размерных страниц (иначе размерная страница дублирует хаб).', max_digits=6, null=True, verbose_name='Фильтр по ширине, м'),
        ),
    ]
