# Generated by Django 5.2.15 on 2026-08-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_cleanup_legacy_public_content'),
        ('seo', '0003_landingpage_filter_length_landingpage_filter_width'),
    ]

    operations = [
    ]
