# Generated by Django 5.2.15 on 2026-08-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_cleanup_legacy_public_content'),
        ('seo', '0004_merge_20260826_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Если выбрать категорию, можно связать страницу с домами или банями', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='catalog.projectcategory', verbose_name='Категория проектов'),
        ),
    ]
