# Generated by Django 5.2.15 on 2026-07-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_project_characteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('callback', 'Заказать звонок'), ('project_order', 'Заказать проект'), ('project_changes', 'Внести правки в проект'), ('own_project', 'Прислать свой проект'), ('calculator', 'Калькулятор'), ('contact_form', 'Форма обратной связи')], default='contact_form', max_length=50, verbose_name='Источник заявки')),
                ('page_url', models.URLField(blank=True, verbose_name='Страница заявки')),
                ('utm_source', models.CharField(blank=True, max_length=255, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=255, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=255, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=255, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, max_length=255, verbose_name='UTM term')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
