# Generated by Django 5.2.15 on 2026-08-25 21:20

import leads.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_consent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadattachment',
            name='file',
            field=models.FileField(storage=leads.storage.PrivateLeadAttachmentStorage(), upload_to='leads/attachments/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
