# Generated by Django 5.2.15 on 2026-08-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leadattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Заполняется автоматически командой anonymize_old_leads (см. LEAD_RETENTION_MONTHS). После обезличивания телефон, комментарий, IP, user-agent и вложения удалены — запись оставлена только для статистики по источникам обращений.', null=True, verbose_name='Обезличена'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
