# Generated by Django 5.2.15 on 2026-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_anonymized_at_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('callback', 'Заказать звонок'), ('project_order', 'Заказать проект'), ('project_changes', 'Внести правки в проект'), ('own_project', 'Прислать свой проект'), ('calculator', 'Калькулятор'), ('contact_form', 'Форма обратной связи'), ('home_phone_consultation', 'Консультация с главной страницы'), ('home_hero_popup', 'Всплывающая форма в баннере на главной'), ('faq_page', 'Вопрос со страницы FAQ'), ('reviews_page', 'Заявка со страницы отзывов')], default='contact_form', max_length=50, verbose_name='Источник заявки'),
        ),
    ]
