# Generated by Django 5.2.15 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_source_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='page_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Страница заявки'),
        ),
    ]
