# Generated by Django 5.2.15 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_page_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Подозрительная'),
        ),
        migrations.AddField(
            model_name='lead',
            name='suspicion_reasons',
            field=models.CharField(blank=True, max_length=255, verbose_name='Почему подозрительная'),
        ),
    ]
