# Generated by Django 5.2.15 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_suspicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quality',
            field=models.CharField(choices=[('unchecked', 'Не проверена'), ('real', 'Реальная'), ('fake', 'Фейк')], default='unchecked', max_length=16, verbose_name='Качество заявки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='metrika_client_id',
            field=models.CharField(blank=True, help_text='Приходит с формой. Если пусто — можно вписать из Вебвизора Метрики (карточка посетителя → ClientID).', max_length=32, verbose_name='ClientID Метрики'),
        ),
        migrations.AddField(
            model_name='lead',
            name='yclid',
            field=models.CharField(blank=True, max_length=100, verbose_name='yclid (клик Директа)'),
        ),
    ]
