# Generated by Django 5.2.15 on 2026-09-17 02:00

from urllib.parse import urlsplit, urlunsplit

import leads.crypto
from django.db import migrations, models


def clean_stored_visit_data(apps, schema_editor):
    """Убирает из уже сохранённых данных то, что больше не храним.

    - page_url: только адрес страницы, без параметров (utm, yclid, etext);
    - журнал админки: название записи раньше содержало телефон заявки.
    """
    Lead = apps.get_model("leads", "Lead")
    for pk, page_url in Lead.objects.exclude(page_url="").values_list("pk", "page_url"):
        parts = urlsplit(page_url)
        clean = urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
        if clean != page_url:
            Lead.objects.filter(pk=pk).update(page_url=clean)

    try:
        LogEntry = apps.get_model("admin", "LogEntry")
        ContentType = apps.get_model("contenttypes", "ContentType")
    except LookupError:
        return

    lead_type = ContentType.objects.filter(app_label="leads", model="lead").first()
    if lead_type is None:
        return
    for pk, object_id in LogEntry.objects.filter(content_type=lead_type).values_list("pk", "object_id"):
        LogEntry.objects.filter(pk=pk).update(object_repr=f"Заявка №{object_id}")


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_quality_and_metrika_ids'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_suspicious',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='metrika_client_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='region',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='suspicion_reasons',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_content',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='utm_term',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='yclid',
        ),
        migrations.AlterField(
            model_name='lead',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Заполняется автоматически командой anonymize_old_leads (см. LEAD_RETENTION_MONTHS). После обезличивания телефон, комментарий, страница и вложения удалены — запись оставлена только для статистики по формам.', null=True, verbose_name='Обезличена'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=leads.crypto.EncryptedPhoneField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.RunPython(clean_stored_visit_data, migrations.RunPython.noop),
    ]
